
server {
    listen 80;
    server_name mdarawsh.42.fr;

    root /var/www/html;
    index index.php;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php${
        include  fastcgi_params;
        fastcgi_pass  wordpress:9000;
        fastcgi_params SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}