services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/YOURLOGIN/data/db
      o: bind

networks:
  inception: